### ISSUE TITLE
Horrible performance on >= 4.0.0

### ISSUE THREAD

**Issue by padinko** [joypixels/emoji-toolkit#1]
We have page with many user inputs

With 544 inputs and use toImage in 3.1.7, it takes `~1.55s`

After we upgrade to 4.0.0.. times are not usable
With 544 input and use toImage in 4.0.0, it takes `~20.8s`

I did some demos (check console for times):
`v3.1.7` - https://jsfiddle.net/76qcth83/ `~0.07s`
`v4.0.0` - https://jsfiddle.net/mzhqyagv/ `~9s`
`v4.5.0` - https://jsfiddle.net/6dba573x/ `~9s`

**Edit**:
I tested v5.0.0 and performance is even worse
https://jsfiddle.net/axsy9b2h/1/ `~15s`

So you moved from `0.07s` to `15s`. Library is now unusable when you need to process more user inputs.

**Comment by caseyahenson** [comment]
@padinko please see v5.0.3 released today. I'm rendering the shortname lookup on load which dramatically speeds up conversions at runtime, albeit at the sacrifice of a slightly longer initialization. Let me know how this is working for you and I'm happy to make further adjustments.

**Comment by padinko** [comment]
`v5.0.3` https://jsfiddle.net/6qxn30ks/ `11s`

11 seconds for 545 short strings is too much.. v3.1.7 can do it under 0.1 seconds

**Comment by caseyahenson** [comment]
I'd strongly recommend converting your emoji in batch rather than calling .toImage within the loop for each individually. For example, when I alter your fiddle like so: 

`strings.forEach(item => {
	const div = document.createElement('div')
        div.innerHTML = item;
	output.appendChild(div);
});
output.innerHTML = joypixels.toImage(output.innerHTML);`

The performance is dramatically improved.

**Comment by zarko-tg** [comment]
Not sure why this issue is closed, even though what I will describe here might be something new.
There's a severe performance issue when making the first call to shortnameToImage once, noticeable in particular in Chrome on Android. It takes about 8 seconds on my Pixel 5 before shortnameToImage returns, and it locks the browsers main thread - no UI updates, no UI interactions in the meantime work. It should be even worse on older devices.

It is easily reproducible just by opening your own example - https://demos.joypixels.com/latest/jsshortnametoimage.html
in Chrome on Android, and clicking on the "Convert" button.

Quite a showstopper for websites or hybrid apps using the lib.

I can open up a new issue if that helps.
